// Generated by GitHub Copilot
/**
 * app.js — Contrôleur principal du dashboard ETF
 * 
 * Responsabilités:
 * - Orchestration des modules (data, chart, KPIs)
 * - Gestion des événements utilisateur
 * - Calcul des KPIs (performance %, CAGR, volatilité, min/max)
 * - Mise à jour dynamique de l'interface
 * - Gestion des erreurs et fallback CSV
 */

const ETFDashboard = (() => {
    // État global
    let state = {
        rawData: [],
        filteredData: [],
        startDate: null,
        endDate: null,
        isLoading: false,
        dataSource: 'none'
    };
    window.currentPeriodReturn = 0;
    window.currentPeriodReturnPerYear = {};
    
    // Éléments DOM
    const DOM = {
        startDateInput: document.getElementById('start-date'),
        endDateInput: document.getElementById('end-date'),
        applyDatesBtn: document.getElementById('apply-dates-btn'),
        refreshBtn: document.getElementById('refresh-btn'),
        csvUploadInput: document.getElementById('csv-upload'),
        errorPanel: document.getElementById('error-panel'),
        errorMessage: document.getElementById('error-message'),
        errorDetail: document.getElementById('error-detail'),
        loadingOverlay: document.getElementById('loading-overlay'),
        loadingText: document.getElementById('loading-text'),
        dataSourceBadge: document.getElementById('data-source-badge'),
        dataSourceLabel: document.getElementById('data-source-label'),
        kpiPerformance: document.getElementById('kpi-performance'),
        kpiGainLoss: document.getElementById('kpi-gain-loss'),
        kpiCAGR: document.getElementById('kpi-cagr'),
        kpiVolatility: document.getElementById('kpi-volatility'),
        kpiMax: document.getElementById('kpi-max'),
        kpiMaxDate: document.getElementById('kpi-max-date'),
        kpiMin: document.getElementById('kpi-min'),
        kpiMinDate: document.getElementById('kpi-min-date')
    };
    
    /**
     * Valide que les éléments DOM critiques existent
     * @private
     */
    const validateDOM = () => {
        console.log('🔍 Validation des éléments DOM...');
        const required = {
            startDateInput: 'input#start-date',
            endDateInput: 'input#end-date',
            applyDatesBtn: 'button#apply-dates-btn'
        };
        
        const missing = [];
        
        for (const [key, selector] of Object.entries(required)) {
            if (!DOM[key]) {
                missing.push(`${key} (${selector})`);
                console.error(`❌ Élément manquant: ${selector}`);
            } else {
                console.log(`✅ ${selector} trouvé`);
            }
        }
        
        if (missing.length > 0) {
            console.error(`⚠️ ${missing.length} éléments critiques manquants:`, missing);
            showError('Erreur: éléments de l\'interface manquants', missing.join(', '));
            return false;
        }
        
        console.log('✅ Tous les éléments critiques trouvés');
        return true;
    };

    /**
     * Initialise l'application
     */
    const init = async () => {
        console.log('🚀 Initialisation du dashboard ETF');
        
        // Valide que les éléments DOM existent
        if (!validateDOM()) {
            return;
        }
        
        // Initialise le calendrier (non-bloquant si erreur)
        try {
            if (typeof CalendarPicker !== 'undefined' && CalendarPicker.init) {
                CalendarPicker.init();
            } else {
                console.warn('⚠️ CalendarPicker non disponible');
            }
        } catch (error) {
            console.error('⚠️ Erreur calendrier:', error);
            // Continue même si le calendrier échoue
        }
        
        // Configure les dates par defaut (1 an)
        setDefaultDateRange();
        
        // Initialise le graphique
        ChartManager.initChart('price-chart');

        // Initialise le module DCA (non-bloquant)
        try {
            if (typeof DCAModule !== 'undefined' && DCAModule.init) {
                DCAModule.init();
            }
        } catch (error) {
            console.warn('⚠️ Module DCA non initialisé:', error);
        }
        
        // Attache les evenements
        attachEventListeners();
        
        // Charge les donnees initiales
        await loadInitialData();
    };
    
    /**
     * Configure la plage de dates par défaut (1 an depuis aujourd'hui)
     * @private
     */
    const setDefaultDateRange = () => {
        console.log('⚙️ Configuration de la plage de dates par défaut...');
        const today = new Date();
        const todayIso = formatDateForInput(today);
        const oneYearAgo = new Date(today.getFullYear() - 1, today.getMonth(), today.getDate());
        
        state.endDate = formatDateForInput(today);
        state.startDate = formatDateForInput(oneYearAgo);
        
        console.log(`📅 Dates: ${formatDateDisplay(oneYearAgo)} → ${formatDateDisplay(today)}`);
        
        // Affiche au format JJ/MM/AAAA dans l'interface (avec vérification)
        if (DOM.startDateInput) {
            DOM.startDateInput.setAttribute('max', todayIso);
            DOM.startDateInput.value = formatDateDisplay(oneYearAgo);
            console.log('✅ Date de début appliquée:', DOM.startDateInput.value);
        } else {
            console.error('❌ DOM.startDateInput est null/undefined');
        }
        
        if (DOM.endDateInput) {
            DOM.endDateInput.setAttribute('max', todayIso);
            DOM.endDateInput.value = formatDateDisplay(today);
            console.log('✅ Date de fin appliquée:', DOM.endDateInput.value);
        } else {
            console.error('❌ DOM.endDateInput est null/undefined');
        }
        
        console.log('✅ Dates par défaut appliquées');
    };

    /**
     * Formate une date pour l'affichage (JJ/MM/AAAA)
     * @private
     */
    const formatDateDisplay = (date) => {
        const day = String(date.getDate()).padStart(2, '0');
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const year = date.getFullYear();
        return `${day}/${month}/${year}`;
    };

    /**
     * Parse une date au format JJ/MM/AAAA pour utilisation interne (YYYY-MM-DD)
     * @private
     */
    const parseDateDisplay = (dateStr) => {
        const parts = dateStr.split('/');
        if (parts.length !== 3) return null;
        
        const day = parseInt(parts[0], 10);
        const month = parseInt(parts[1], 10) - 1;
        const year = parseInt(parts[2], 10);
        
        const date = new Date(year, month, day);
        return formatDateForInput(date);
    };
    
    /**
     * Formate une date pour l'input HTML (YYYY-MM-DD)
     * @private
     */
    const formatDateForInput = (date) => {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    };
    
    /**
     * Attache les écouteurs d'événements
     * @private
     */
    const attachEventListeners = () => {
        if (DOM.applyDatesBtn) {
            DOM.applyDatesBtn.addEventListener('click', handleApplyDates);
        }
        if (DOM.refreshBtn) {
            DOM.refreshBtn.addEventListener('click', handleRefreshData);
        }
        if (DOM.csvUploadInput) {
            DOM.csvUploadInput.addEventListener('change', handleCSVUpload);
        }
        
        console.log('✅ Event listeners attachés');
    };
    
    /**
     * Gestionnaire: Appliquer la nouvelle plage de dates
     * @private
     */
    const handleApplyDates = async () => {
        const startDateDisplay = DOM.startDateInput.value;
        const endDateDisplay = DOM.endDateInput.value;
        
        // Validation basique
        if (!startDateDisplay || !endDateDisplay) {
            showError('Veuillez selectionner les deux dates');
            return;
        }
        
        // Convertit au format interne YYYY-MM-DD
        const startDate = parseDateDisplay(startDateDisplay);
        let endDate = parseDateDisplay(endDateDisplay);
        
        if (!startDate || !endDate) {
            showError('Format de date invalide (utilisez JJ/MM/AAAA)');
            return;
        }

        const todayIso = formatDateForInput(new Date());
        if (endDate > todayIso) {
            endDate = todayIso;
            if (DOM.endDateInput) {
                DOM.endDateInput.value = formatDateDisplay(new Date(`${todayIso}T00:00:00`));
            }
        }
        
        if (startDate >= endDate) {
            showError('La date de debut doit etre anterieure a la date de fin');
            return;
        }
        
        state.startDate = startDate;
        state.endDate = endDate;
        
        // Filtre et met a jour
        filterAndUpdate();
    };
    
    /**
     * Gestionnaire: Actualiser les données (vider le cache)
     * @private
     */
    const handleRefreshData = async () => {
        console.log('⟳ Actualisation des données...');
        DOM.refreshBtn.classList.add('loading');
        
        try {
            DataManager.clearCache(state.startDate, state.endDate);
            state.rawData = [];
            await loadInitialData();
            DOM.refreshBtn.classList.remove('loading');
        } catch (error) {
            showError('Erreur lors de l\'actualisation: ' + error.message);
            DOM.refreshBtn.classList.remove('loading');
        }
    };
    
    /**
     * Gestionnaire: Téléchargement de fichier CSV
     * @private
     */
    const handleCSVUpload = async (event) => {
        const file = event.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const csvText = e.target.result;
                const data = DataManager.parseCSV(csvText);
                
                if (!data || data.length === 0) {
                    showError('Format CSV invalide. Attendu: Date, Open, High, Low, Close, Volume');
                    return;
                }
                
                state.rawData = data;
                state.dataSource = 'csv';
                updateDataSourceBadge('csv');
                hideError();
                console.log(`✓ ${data.length} lignes chargées depuis CSV`);
                
                // Réinitialise la plage de dates pour couvrir tout le CSV
                if (data.length > 0) {
                    state.startDate = data[0].date;
                    state.endDate = data[data.length - 1].date;
                    DOM.startDateInput.value = formatDateDisplay(new Date(`${state.startDate}T00:00:00`));
                    DOM.endDateInput.value = formatDateDisplay(new Date(`${state.endDate}T00:00:00`));
                }
                
                filterAndUpdate();
            } catch (error) {
                showError('Erreur lors du parsing du CSV: ' + error.message);
            }
        };
        reader.readAsText(file);
    };
    
    /**
     * Charge les données initiales depuis Yahoo Finance ou le cache
     * @private
     */
    const loadInitialData = async () => {
        console.log('📊 Démarrage du chargement des données...');
        state.isLoading = true;
        showLoading('Récupération des données CW8.PA via Yahoo Finance…');
        
        try {
            console.log(`🔄 Requête: ${state.startDate} → ${state.endDate}`);
            const result = await DataManager.fetchData(state.startDate, state.endDate);
            console.log(`✅ Données reçues (${result.data.length} points, source: ${result.source})`);
            
            state.rawData = result.data;
            state.dataSource = result.source || 'live';
            updateDataSourceBadge(state.dataSource);
            hideError();
            filterAndUpdate();
        } catch (error) {
            console.error('❌ Erreur fetch:', error);
            showError(
                'Impossible de récupérer les données depuis Yahoo Finance.',
                error.message
            );
            state.isLoading = false;
        } finally {
            hideLoading();
        }
    };
    
    /**
     * Filtre les données et met à jour tous les éléments
     * @private
     */
    const filterAndUpdate = () => {
        if (!state.rawData || state.rawData.length === 0) {
            showError('Aucune donnée disponible');
            return;
        }
        
        state.filteredData = DataManager.filterByDateRange(
            state.rawData,
            state.startDate,
            state.endDate
        );
        
        if (state.filteredData.length === 0) {
            showError('Aucune donnée pour la plage sélectionnée');
            return;
        }
        
        // Met à jour le graphique
        ChartManager.updateChart(state.filteredData);
        ChartManager.updateChartAccessibility(state.filteredData);
        
        // Recalcule et met à jour tous les KPIs
        updateAllKPIs();

        // Recalcule le DCA sur la période filtrée
        if (typeof DCAModule !== 'undefined' && DCAModule.calculate) {
            DCAModule.calculate({
                data: state.filteredData,
                startDate: state.startDate,
                endDate: state.endDate
            });
        }
        
        state.isLoading = false;
        hideError();
    };
    
    /**
     * Met à jour tous les KPIs
     * @private
     */
    const updateAllKPIs = () => {
        if (!state.filteredData || state.filteredData.length < 2) return;
        
        const metrics = calculateMetrics(state.filteredData);
        
        // Performance %
        const perfPercent = metrics.performance.toFixed(2);
        DOM.kpiPerformance.textContent = (perfPercent >= 0 ? '+' : '') + perfPercent;
        DOM.kpiPerformance.className = 'kpi-value ' + (metrics.performance >= 0 ? 'positive' : 'negative');
        window.currentPeriodReturn = Number(metrics.performance);
        window.currentPeriodReturnPerYear = calculateYearlyReturns(state.filteredData, state.startDate, state.endDate);
        
        // Gain/Perte en EUR
        const gainLoss = metrics.gainLoss.toFixed(2);
        DOM.kpiGainLoss.textContent = (metrics.gainLoss >= 0 ? '+' : '') + gainLoss;
        DOM.kpiGainLoss.className = 'kpi-value ' + (metrics.gainLoss >= 0 ? 'positive' : 'negative');
        
        // CAGR
        const cagr = metrics.cagr.toFixed(2);
        DOM.kpiCAGR.textContent = (metrics.cagr >= 0 ? '+' : '') + cagr;
        DOM.kpiCAGR.className = 'kpi-value ' + (metrics.cagr >= 0 ? 'positive' : 'negative');
        
        // Volatilité
        DOM.kpiVolatility.textContent = metrics.volatility.toFixed(2);
        DOM.kpiVolatility.className = 'kpi-value';
        
        // Prix maximum et date
        DOM.kpiMax.textContent = '€' + metrics.maxPrice.toFixed(2);
        DOM.kpiMax.className = 'kpi-value';
        DOM.kpiMaxDate.textContent = metrics.maxDate;
        
        // Prix minimum et date
        DOM.kpiMin.textContent = '€' + metrics.minPrice.toFixed(2);
        DOM.kpiMin.className = 'kpi-value';
        DOM.kpiMinDate.textContent = metrics.minDate;
    };

    /**
     * Calcule le rendement (%) de chaque année présente dans la période filtrée.
     * @param {Array} data
     * @param {string} startDate
     * @param {string} endDate
     * @returns {Object}
     */
    const calculateYearlyReturns = (data, startDate, endDate) => {
        if (!Array.isArray(data) || data.length < 2 || !startDate || !endDate) {
            return {};
        }

        const firstByYear = new Map();
        const lastByYear = new Map();

        for (const row of data) {
            const year = String(new Date(`${row.date}T00:00:00`).getFullYear());
            if (!firstByYear.has(year)) {
                firstByYear.set(year, row);
            }
            lastByYear.set(year, row);
        }

        const startYear = String(new Date(`${startDate}T00:00:00`).getFullYear());
        const endYear = String(new Date(`${endDate}T00:00:00`).getFullYear());
        const result = {};

        for (const year of firstByYear.keys()) {
            const firstRow = year === startYear ? data[0] : firstByYear.get(year);
            const lastRow = year === endYear ? data[data.length - 1] : lastByYear.get(year);
            const startPrice = Number(firstRow?.close);
            const endPrice = Number(lastRow?.close);

            if (Number.isFinite(startPrice) && startPrice > 0 && Number.isFinite(endPrice)) {
                result[year] = ((endPrice - startPrice) / startPrice) * 100;
            }
        }

        return result;
    };
    
    /**
     * Calcule toutes les métriques financières
     * @private
     */
    const calculateMetrics = (data) => {
        const closeStart = data[0].close;
        const closeEnd = data[data.length - 1].close;
        const dates = data.map(d => new Date(d.date));
        const daysDiff = Math.ceil((dates[dates.length - 1] - dates[0]) / (1000 * 60 * 60 * 24));
        const yearsDiff = daysDiff / 365.25;
        
        // Performance %
        const performance = ((closeEnd - closeStart) / closeStart) * 100;
        
        // Gain/Perte en EUR
        const gainLoss = closeEnd - closeStart;
        
        // CAGR (Compound Annual Growth Rate)
        const cagr = (Math.pow(closeEnd / closeStart, 1 / yearsDiff) - 1) * 100;
        
        // Volatilité (écart-type annualisé des rendements journaliers)
        const dailyReturns = [];
        for (let i = 1; i < data.length; i++) {
            const ret = (data[i].close - data[i - 1].close) / data[i - 1].close;
            dailyReturns.push(ret);
        }
        
        const avgReturn = dailyReturns.reduce((a, b) => a + b, 0) / dailyReturns.length;
        const variance = dailyReturns.reduce((sum, ret) => sum + Math.pow(ret - avgReturn, 2), 0) / dailyReturns.length;
        const stdDev = Math.sqrt(variance);
        const volatility = stdDev * Math.sqrt(252) * 100; // 252 jours de trading par an
        
        // Min et Max
        const prices = data.map(d => d.close);
        const minPrice = Math.min(...prices);
        const maxPrice = Math.max(...prices);
        const minDate = data.find(d => d.close === minPrice).date;
        const maxDate = data.find(d => d.close === maxPrice).date;
        
        return {
            performance,
            gainLoss,
            cagr,
            volatility,
            minPrice,
            maxPrice,
            minDate,
            maxDate
        };
    };
    
    /**
     * Affiche le panneau d'erreur avec détail optionnel
     * @param {string} message - Message principal
     * @param {string} [detail] - Conseil ou détail technique (ex: cause CORS)
     * @private
     */
    const showError = (message, detail = '') => {
        console.error('❌ Erreur:', message, detail);
        if (DOM.errorPanel) {
            DOM.errorPanel.classList.remove('hidden');
        }
        if (DOM.errorMessage) {
            DOM.errorMessage.textContent = message;
        }
        if (detail) {
            if (DOM.errorDetail) {
                DOM.errorDetail.textContent = detail;
                DOM.errorDetail.classList.remove('hidden');
            }
        } else {
            if (DOM.errorDetail) {
                DOM.errorDetail.classList.add('hidden');
            }
        }
    };
    
    /**
     * Masque le panneau d'erreur
     * @private
     */
    const hideError = () => {
        if (DOM.errorPanel) {
            DOM.errorPanel.classList.add('hidden');
        }
    };

    /**
     * Affiche l'overlay de chargement
     * @param {string} text - Message affiché pendant le chargement
     * @private
     */
    const showLoading = (text = 'Chargement…') => {
        if (DOM.loadingText) {
            DOM.loadingText.textContent = text;
        }
        if (DOM.loadingOverlay) {
            DOM.loadingOverlay.classList.remove('hidden');
        }
    };

    /**
     * Masque l'overlay de chargement
     * @private
     */
    const hideLoading = () => {
        if (DOM.loadingOverlay) {
            DOM.loadingOverlay.classList.add('hidden');
        }
    };

    /**
     * Met à jour le badge indiquant la source des données
     * @param {'live'|'cached'|'csv'|'none'} source
     * @private
     */
    const updateDataSourceBadge = (source) => {
        const labels = {
            live:   'Données Yahoo Finance en direct',
            cached: 'Données depuis le cache (< 24h)',
            csv:    'Données importées via CSV',
            demo:   '📊 Données de démonstration',
            none:   'En attente…'
        };
        
        if (DOM.dataSourceBadge) {
            DOM.dataSourceBadge.className = `data-source-badge ${source}`;
        }
        if (DOM.dataSourceLabel) {
            DOM.dataSourceLabel.textContent = labels[source] || labels.none;
        }
        
        console.log(`📊 Source de données: ${labels[source]}`);
    };
    
    return {
        init
    };
})();

// Initialise l'application au chargement du DOM
document.addEventListener('DOMContentLoaded', () => {
    ETFDashboard.init();
});
