// Generated by GitHub Copilot
/**
 * portfolio.js — Module Portefeuille multi-ETF
 *
 * - Volet gauche repliable (gros bouton) pour éditer un portefeuille (jusqu'à 10 ETF)
 * - Sélection progressive via listes déroulantes + champs % (rebalance auto, somme 100%)
 * - Camembert (doughnut Chart.js) de la répartition
 * - Bouton Confirmer : construit une série composite (capital de départ en €)
 *   et recalcule tout le dashboard via ETFDashboard.applyPortfolioSeries()
 */

const PortfolioModule = (() => {
    const MAX_ETFS = 10;

    const PALETTE = [
        '#f0b429', '#10b981', '#6366f1', '#ef4444', '#8b5cf6',
        '#06b6d4', '#ec4899', '#84cc16', '#f97316', '#14b8a6'
    ];

    const DETAIL_PALETTE = [
        '#10b981', '#60a5fa', '#f97316', '#a78bfa', '#22d3ee',
        '#f43f5e', '#84cc16', '#f59e0b', '#38bdf8', '#c084fc'
    ];

    let catalog = [];
    let selections = []; // [{ id, weight }]
    let pieChart = null;

    const DOM = {
        panel: null,
        toggle: null,
        body: null,
        rows: null,
        add: null,
        pie: null,
        warning: null,
        confirm: null,
        reset: null
    };

    const round1 = (v) => Math.round(v * 10) / 10;
    const round2 = (v) => Math.round(v * 100) / 100;

    const getEtf = (id) => catalog.find((e) => e.id === id);

    /** Répartit équitablement les poids (100/n). */
    const rebalanceEqual = () => {
        const n = selections.length;
        if (n === 0) return;
        const w = round1(100 / n);
        selections.forEach((s, i) => {
            s.weight = (i === n - 1) ? round1(100 - w * (n - 1)) : w;
        });
    };

    /** Rebalance proportionnel des autres après édition manuelle d'un poids. */
    const rebalanceProportional = (index, newVal) => {
        const val = Math.max(0, Math.min(100, newVal));
        const others = selections.filter((_, i) => i !== index);
        const sumOthers = others.reduce((acc, s) => acc + s.weight, 0);
        const remaining = 100 - val;
        if (others.length > 0) {
            if (sumOthers > 0) {
                others.forEach((s) => { s.weight = round1(s.weight / sumOthers * remaining); });
            } else {
                const eq = round1(remaining / others.length);
                others.forEach((s) => { s.weight = eq; });
            }
        }
        selections[index].weight = round1(val);
        fixRoundingTo100();
    };

    /** Corrige les arrondis pour que la somme fasse exactement 100. */
    const fixRoundingTo100 = () => {
        if (selections.length === 0) return;
        const sum = selections.reduce((acc, s) => acc + s.weight, 0);
        const diff = round1(100 - sum);
        if (diff !== 0) {
            selections[selections.length - 1].weight = round1(selections[selections.length - 1].weight + diff);
        }
    };

    /** Options d'un select pour les ETF non encore sélectionnés. */
    const availableOptions = (selectedId) => {
        const used = new Set(selections.map((s) => s.id));
        return catalog
            .filter((e) => !used.has(e.id) || e.id === selectedId)
            .map((e) => {
                const sel = e.id === selectedId ? ' selected' : '';
                const tag = e.source === 'seed' ? ' (test)' : '';
                return `<option value="${e.id}"${sel}>${e.name}${tag}</option>`;
            })
            .join('');
    };

    /** Rendu des lignes ETF sélectionnées + la liste déroulante d'ajout. */
    const render = () => {
        if (!DOM.rows || !DOM.add) return;

        // Lignes des ETF sélectionnés (nom + champ %)
        DOM.rows.innerHTML = selections.map((s, i) => {
            const etf = getEtf(s.id);
            const name = etf ? etf.name : s.id;
            return `
                <div class="pf-row" data-index="${i}">
                    <span class="pf-swatch" style="background:${PALETTE[i % PALETTE.length]}"></span>
                    <span class="pf-name" title="${name}">${name}</span>
                    <div class="pf-weight">
                        <input type="number" class="pf-weight-input" data-index="${i}"
                               min="0" max="100" step="0.1" value="${s.weight}">
                        <span class="pf-pct">%</span>
                    </div>
                    <button type="button" class="pf-remove" data-index="${i}" title="Retirer">✕</button>
                </div>
            `;
        }).join('');

        // Liste déroulante d'ajout (si place disponible)
        const used = new Set(selections.map((s) => s.id));
        const remaining = catalog.filter((e) => !used.has(e.id));
        if (selections.length < MAX_ETFS && remaining.length > 0) {
            DOM.add.innerHTML = `
                <label class="pf-add-label">Ajouter un ETF</label>
                <select class="pf-add-select" id="pf-add-select">
                    <option value="">— Sélectionner un ETF —</option>
                    ${remaining.map((e) => {
                        const tag = e.source === 'seed' ? ' (test)' : '';
                        return `<option value="${e.id}">${e.name}${tag}</option>`;
                    }).join('')}
                </select>
            `;
        } else {
            DOM.add.innerHTML = selections.length >= MAX_ETFS
                ? '<p class="pf-hint">Maximum de 10 ETF atteint.</p>'
                : '';
        }

        attachRowEvents();
        updatePie();
    };

    /** Attache les événements aux champs % , boutons retirer et select d'ajout. */
    const attachRowEvents = () => {
        DOM.rows.querySelectorAll('.pf-weight-input').forEach((input) => {
            input.addEventListener('change', (e) => {
                const idx = Number(e.target.dataset.index);
                rebalanceProportional(idx, Number(e.target.value) || 0);
                render();
            });
        });
        DOM.rows.querySelectorAll('.pf-remove').forEach((btn) => {
            btn.addEventListener('click', (e) => {
                const idx = Number(e.target.dataset.index);
                selections.splice(idx, 1);
                if (selections.length > 0) {
                    // Renormalise proportionnellement pour garder 100%
                    const sum = selections.reduce((acc, s) => acc + s.weight, 0);
                    if (sum > 0) {
                        selections.forEach((s) => { s.weight = round1(s.weight / sum * 100); });
                    } else {
                        rebalanceEqual();
                    }
                    fixRoundingTo100();
                }
                render();
            });
        });

        const addSelect = document.getElementById('pf-add-select');
        if (addSelect) {
            addSelect.addEventListener('change', (e) => {
                const id = e.target.value;
                if (!id) return;
                if (selections.length >= MAX_ETFS) return;
                selections.push({ id, weight: 0 });
                rebalanceEqual(); // 1->100, 2->50/50, 3->33.3...
                render();
            });
        }
    };

    /** Met à jour le camembert (doughnut) de répartition. */
    const updatePie = () => {
        if (!DOM.pie || typeof Chart === 'undefined') return;

        const labels = selections.map((s) => {
            const etf = getEtf(s.id);
            return etf ? etf.name : s.id;
        });
        const data = selections.map((s) => s.weight);
        const colors = selections.map((_, i) => PALETTE[i % PALETTE.length]);

        if (pieChart) {
            pieChart.data.labels = labels;
            pieChart.data.datasets[0].data = data;
            pieChart.data.datasets[0].backgroundColor = colors;
            pieChart.update();
            return;
        }

        pieChart = new Chart(DOM.pie.getContext('2d'), {
            type: 'doughnut',
            data: {
                labels,
                datasets: [{
                    data,
                    backgroundColor: colors,
                    borderColor: '#1a1a1a',
                    borderWidth: 2,
                    hoverOffset: 6
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                cutout: '60%',
                plugins: {
                    legend: {
                        position: 'bottom',
                        labels: { color: '#f0f0f0', font: { size: 11 }, boxWidth: 12, padding: 8 }
                    },
                    tooltip: {
                        callbacks: {
                            label: (ctx) => `${ctx.label}: ${ctx.parsed.toFixed(1)}%`
                        }
                    }
                }
            }
        });
    };

    /**
     * Extrait les dates mensuelles (premier jour du mois ou premier jour disponible) depuis une liste de dates.
     */
    const getMonthlyDates = (allDates) => {
        if (!allDates || allDates.length === 0) return [];
        
        const monthly = [];
        let lastMonth = null;
        
        for (const dateStr of allDates) {
            const [year, month] = dateStr.substring(0, 7).split('-');
            const monthKey = `${year}-${month}`;
            if (monthKey !== lastMonth) {
                monthly.push(dateStr);
                lastMonth = monthKey;
            }
        }
        
        return monthly;
    };

    /**
     * Construit la série composite DCA mensuel pondéré.
     * Pour chaque mois : investit (monthlyAmount * weight%) à chaque ETF
     * Accumule les parts au fil du temps
     * Valorise la position chaque jour
     */
    const buildMonthlyDCASeries = (monthlyAmount) => {
        if (selections.length === 0) return null;

        const etfs = selections.map((s) => ({
            weight: s.weight,
            etf: getEtf(s.id)
        })).filter((x) => x.etf && Array.isArray(x.etf.data) && x.etf.data.length);

        if (etfs.length === 0) return null;

        // Normalise les poids (somme = 1)
        const totalW = etfs.reduce((acc, x) => acc + x.weight, 0) || 1;
        etfs.forEach((x) => { x.w = x.weight / totalW; });

        // Map date -> close pour chaque ETF
        etfs.forEach((x) => {
            x.map = new Map(x.etf.data.map((d) => [d.date, d.close]));
        });

        // Intersection des dates
        const first = etfs[0].etf.data.map((d) => d.date);
        const commonDates = first.filter((date) => etfs.every((x) => x.map.has(date)));
        commonDates.sort();
        
        if (commonDates.length === 0) return null;

        const baseDate = commonDates[0];
        
        // Extraire les dates mensuelles
        const monthlyDates = getMonthlyDates(commonDates);
        if (monthlyDates.length === 0) return null;

        // Initialiser l'accumulateur de parts pour chaque ETF
        etfs.forEach((x) => {
            x.accumulatedShares = 0;
        });

        // Construire la série DCA : pour chaque date, accumuler les parts puis valoriser
        const rows = commonDates.map((date) => {
            // Vérifier si c'est une date d'investissement mensuel
            if (monthlyDates.includes(date)) {
                // Investir monthlyAmount * weight% dans chaque ETF
                for (const x of etfs) {
                    const amountForEtf = (monthlyAmount * x.w);
                    const priceAtDate = x.map.get(date);
                    if (priceAtDate > 0) {
                        x.accumulatedShares += amountForEtf / priceAtDate;
                    }
                }
            }

            // Valoriser le portefeuille à cette date
            let totalValue = 0;
            for (const x of etfs) {
                const priceAtDate = x.map.get(date);
                totalValue += x.accumulatedShares * priceAtDate;
            }

            const eur = round2(totalValue);
            return { date, open: eur, high: eur, low: eur, close: eur, volume: 0 };
        });

        // Construire les séries détaillées (contribution de chaque ETF)
        const detailSeries = etfs.map((x, i) => {
            const etfName = x.etf?.name || x.etf?.id || `ETF ${i + 1}`;
            const dataByDate = {};
            
            commonDates.forEach((date) => {
                const priceAtDate = x.map.get(date);
                const etfValue = round2(x.accumulatedShares * priceAtDate);
                dataByDate[date] = etfValue;
            });

            const points = commonDates.map((date) => dataByDate[date]);

            return {
                label: etfName,
                data: points,
                dataByDate,
                borderColor: DETAIL_PALETTE[i % DETAIL_PALETTE.length],
                backgroundColor: 'transparent',
                borderWidth: 1.3,
                fill: false,
                tension: 0.25,
                pointRadius: 0,
                pointHoverRadius: 3
            };
        });

        return { rows, baseDate, detailSeries };
    };

    /**
     * Construit la série composite (capital de départ en €) sur l'intersection
     * des dates des ETF sélectionnés.
     * @returns {{rows: Array, baseDate: string} | null}
     */
    const buildComposite = () => {
        // Lire le montant mensuel depuis l'input
        const monthlyAmountInput = document.getElementById('portfolio-monthly-amount');
        const monthlyAmount = monthlyAmountInput ? parseFloat(monthlyAmountInput.value) || 1100 : 1100;
        
        return buildMonthlyDCASeries(monthlyAmount);
    };

    /** Confirme le portefeuille : construit la série et recalcule le dashboard. */
    const confirm = () => {
        if (!DOM.warning) return;
        DOM.warning.textContent = '';
        DOM.warning.classList.remove('visible');

        if (selections.length === 0) {
            showWarning('Sélectionnez au moins un ETF.');
            return;
        }

        const composite = buildComposite();
        if (!composite || composite.rows.length === 0) {
            showWarning('Aucune période commune aux ETF sélectionnés.');
            return;
        }

        if (typeof ETFDashboard === 'undefined' || !ETFDashboard.applyPortfolioSeries) {
            showWarning('Dashboard indisponible.');
            return;
        }

        const label = selections.length === 1
            ? `Portefeuille : ${getEtf(selections[0].id)?.name || selections[0].id}`
            : `Portefeuille personnalisé (${selections.length} ETF)`;

        const res = ETFDashboard.applyPortfolioSeries(composite.rows, label);

        if (typeof ChartManager !== 'undefined' && typeof ChartManager.setDetailDatasets === 'function') {
            ChartManager.setDetailDatasets(composite.detailSeries || []);
        }

        if (res.clamped) {
            showWarning(`⚠️ Certains ETF n'ont pas de données avant le ${formatFr(res.min)}. La période de début a été ajustée.`);
        } else {
            showWarning(`✅ Portefeuille appliqué (données depuis le ${formatFr(composite.baseDate)}).`, true);
        }
    };

    const showWarning = (msg, ok = false) => {
        if (!DOM.warning) return;
        DOM.warning.textContent = msg;
        DOM.warning.classList.add('visible');
        DOM.warning.classList.toggle('ok', ok);
    };

    const formatFr = (iso) => {
        if (!iso) return '';
        const d = new Date(`${iso}T00:00:00`);
        return d.toLocaleDateString('fr-FR', { day: '2-digit', month: 'long', year: 'numeric' });
    };

    /** Réinitialise sur le portefeuille par défaut (CW8 seul). */
    const resetDefault = () => {
        selections = [];

        const msciWorld = catalog.find((e) => e.id === 'CW8.PA');
        const msciEmerging = catalog.find((e) => e.id === 'PAEEM.PA');
        const stoxx600 = catalog.find((e) => e.id === 'ETSZ.DE');

        if (msciWorld && msciEmerging && stoxx600) {
            selections.push({ id: msciWorld.id, weight: 50 });
            selections.push({ id: msciEmerging.id, weight: 25 });
            selections.push({ id: stoxx600.id, weight: 25 });
        } else {
            const cw8 = catalog.find((e) => e.id === 'CW8.PA') || catalog[0];
            if (cw8) {
                selections.push({ id: cw8.id, weight: 100 });
            }
        }

        render();
    };

    /** Initialise le module. */
    const init = () => {
        catalog = Array.isArray(window.ETF_CATALOG) ? window.ETF_CATALOG : [];
        if (catalog.length === 0) {
            console.warn('⚠️ ETF_CATALOG vide : portefeuille désactivé');
            return;
        }

        DOM.panel = document.getElementById('portfolio-panel');
        DOM.toggle = document.getElementById('portfolio-toggle');
        DOM.body = document.getElementById('portfolio-body');
        DOM.rows = document.getElementById('portfolio-rows');
        DOM.add = document.getElementById('portfolio-add');
        DOM.pie = document.getElementById('portfolio-pie');
        DOM.warning = document.getElementById('portfolio-warning');
        DOM.confirm = document.getElementById('portfolio-confirm');
        DOM.reset = document.getElementById('portfolio-reset');

        if (!DOM.panel || !DOM.rows) {
            console.warn('⚠️ Éléments du volet portefeuille manquants');
            return;
        }

        if (DOM.toggle) {
            DOM.toggle.addEventListener('click', () => {
                DOM.panel.classList.toggle('collapsed');
                const collapsed = DOM.panel.classList.contains('collapsed');
                DOM.toggle.setAttribute('aria-expanded', String(!collapsed));
            });
        }

        const detailsToggleBtn = document.getElementById('toggle-etf-details');
        if (detailsToggleBtn) {
            detailsToggleBtn.addEventListener('click', () => {
                if (typeof ChartManager === 'undefined' || typeof ChartManager.toggleDetailDatasets !== 'function') {
                    return;
                }
                const visible = ChartManager.toggleDetailDatasets();
                detailsToggleBtn.textContent = visible
                    ? 'Masquer les courbes ETF'
                    : 'Afficher les courbes ETF';
                detailsToggleBtn.setAttribute('aria-pressed', String(visible));
            });
        }
        if (DOM.confirm) DOM.confirm.addEventListener('click', confirm);
        if (DOM.reset) DOM.reset.addEventListener('click', resetDefault);

        // Sur mobile, replier le volet portefeuille par défaut
        if (window.matchMedia('(max-width: 1200px)').matches) {
            DOM.panel.classList.add('collapsed');
            if (DOM.toggle) DOM.toggle.setAttribute('aria-expanded', 'false');
        }

        // Portefeuille initial : CW8 à 100%
        resetDefault();
        console.log('✅ Module Portefeuille initialisé');
    };

    return { init };
})();

document.addEventListener('DOMContentLoaded', () => {
    PortfolioModule.init();
});
