// Generated by GitHub Copilot
/**
 * sw.js — Service Worker (PWA)
 * Stratégie: cache-first pour l'app shell, network-first en repli.
 * Bump CACHE_VERSION à chaque déploiement pour rafraîchir les fichiers.
 */

const CACHE_VERSION = 'etf-dashboard-v2';
const APP_SHELL = [
    './',
    './index.html',
    './style.css',
    './data-snapshot.js',
    './data.js',
    './chart.js',
    './dca.js',
    './calendar.js',
    './app-dca.js',
    './portfolio.js',
    './manifest.json',
    './icon-192.png',
    './icon-512.png'
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_VERSION).then((cache) => cache.addAll(APP_SHELL)).then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((keys) => Promise.all(
            keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k))
        )).then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    // Ne pas mettre en cache les appels réseau vers Yahoo/proxies (données live)
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) {
        return; // laisse passer les requêtes tierces (fetch live)
    }

    event.respondWith(
        caches.match(request).then((cached) => {
            if (cached) return cached;
            return fetch(request).then((response) => {
                const copy = response.clone();
                caches.open(CACHE_VERSION).then((cache) => cache.put(request, copy)).catch(() => {});
                return response;
            }).catch(() => cached);
        })
    );
});
